### PR TITLE
Update for January 2021

### PR DESCRIPTION
**Pull request by skalee**
Re-importing concepts for #7 due to #12.

### CODE REVIEW

**Comment by skalee** [comment]
FYI @ronaldtse, there are other changes too. For example, "Met Ocean DWG" has been renamed to "OGC Met Ocean DWG". Are there further changes/imports expected?

**Comment by ronaldtse** [comment]
Don't think so, this should be the last set of changes. Thanks!

**Comment by skalee** [comment]
@ronaldtse It seems they are still editing the spreadsheet. For instance, few hours ago they added term 40 „CEOS Working Group on Capacity Building and Data Democracy” and fixed a few obvious typos.

What's worse, it looks like the spreadsheet can be edited by anonymous users, which means that I could introduce accidental changes when I was browsing data to compare them with produced YAML concepts (I wasn't signed in). I know that I pressed a wrong key one or two times, but I also pressed "undo" right after that. From looking at changes, history I don't think I broke anything, but I am not sure of that.

**Comment by skalee** [comment]
I'll make another import when the final form will be available.

**Comment by ronaldtse** [comment]
@skalee I made the minor changes you saw. The permissions are certainly wrong... it shouldn't be publicly editable.

**Comment by ronaldtse** [comment]
The sheet is now locked

**Pull request merged**
